[package]
name = "stark-anat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.8"
itertools = "0.10.5"
ruint = "1.10.1"

[dev-dependencies]

