name: test

on:
  workflow_call: {}

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-test
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v3
      - name: Setup rust env
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: llvm-tools-preview
          override: true
      - name: Retrieve cached dependencies
        uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@nextest
      - name: run tests
        run: make test
